### ISSUE TITLE
Private cloud configuration not updated in sphere-stack.sh 

### ISSUE THREAD

**Issue by miguelaferreira** [ninjasphere/sphere-stack#4]
After creating the account and the application in the douitsu service, the tutorial continues with `./sphere-stack.sh edit` and `./sphere-stack.sh update application-table`.
However, the first command will not update the app_XX and sk_XX values in  `sphere-stack.sh` and that will affect the ability of the second command to properly update the msyql DB.

I've worked around it by manually updating the script with the values I read from douitsu.

**Comment by jonseymour** [comment]
G'day Miguel,

The intent with `./sphere-stack.sh edit` is to open editor on the relevant configuration file to allow you to define those variables. Did this not happen for you?

**Comment by miguelaferreira** [comment]
It did happen, and I did edit the variables. However, then next two steps did not take the new values that replaced `app_XX` and `sk_XX` into account. In turn that made the cloud services unusable.

I fixed it by editing the `./sphere-stack.sh`, adding those values in the `generate()`function, and re-running the two mentioned steps.

**Comment by jonseymour** [comment]
Ok, thanks for the info. I'll have another look at it.

**Comment by jonseymour** [comment]
Thanks for the report - should be fixed by 1a2bdfc.
